媠聲校對檔案毋免--ê攏mài khok-pì。
i3thuan5/SuiSiann-KauTui pull request #346
Opened 2022-06-21 07:24 UTC by sih4sing5hong5

2022-06-22 06:01 UTC, a8568730 requested changes
👍🏼

2022-06-22 06:01 UTC, a8568730 commented on .dockerignore
> +
Kiann làu-kau, beh tsham-khó Kàu-tián--bô?
```
docker-compose.yml
Dockerfile
*/venv/
*/media/
*/too/
*.mo
.tox/
.git/
*/__pycache__/

*/node_modules/
*.sql.gz
*.tar
*.map
autuan/static/css/
```

2022-06-22 06:24 UTC, sih4sing5hong5 commented on .dockerignore
> +
f9edafda4406ae10dcb4e42519779e1ecf3646ec 有改`compose`，這專案bô JS, mo，所以就毋免--ah

2022-06-23 07:34 UTC, a8568730 commented on .dockerignore
> +
👍🏼

2022-06-23 07:34 UTC, a8568730 approved these changes
👍🏼

2022-06-23 07:34 UTC, merged